spring:
  profiles:
    active: dev
  application:
    name: api-blog-pessoal

  # Configurações globais do Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration

  # Configurações globais do Jackson para datas
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/Sao_Paulo

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: when_authorized
  info:
    env:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
  enable-hateoas: false



