-- V3: Estrutura DDL para Categorias, Tags e Slugs (Compatível com H2)
CREATE TABLE categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL UNIQUE,
    slug VARCHAR(60) NOT NULL UNIQUE
);

CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(30) NOT NULL UNIQUE
);

ALTER TABLE posts ADD COLUMN slug VARCHAR(160) UNIQUE;
ALTER TABLE posts ADD COLUMN categoria_id BIGINT;
ALTER TABLE posts ADD CONSTRAINT fk_post_categoria FOREIGN KEY (categoria_id) REFERENCES categorias(id);

CREATE TABLE posts_tags (
    post_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    PRIMARY KEY (post_id, tag_id),
    CONSTRAINT fk_post_tag_post FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
    CONSTRAINT fk_post_tag_tag FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
);
